### ISSUE TITLE
TypeError on start

### ISSUE THREAD

**Issue by astopy** [zooniverse/cellect_panoptes#8]
See below:

    /cellect_panoptes/start:43:in `system': no implicit conversion of Fixnum into String (TypeError)
    	from /cellect_panoptes/start:43:in `<main>'

**Comment by camallen** [comment]
what version of cellect panoptes is this using? this should have been fixed, https://github.com/zooniverse/cellect_panoptes/commits/master

**Comment by astopy** [comment]
That's using the latest build.

**Comment by camallen** [comment]
Strange - i'm testing the lastest build on my machine now.

**Comment by camallen** [comment]
it's working on my machine - where are you getting this error, on your machine?

**Comment by camallen** [comment]
Could be the config file is missing, https://github.com/zooniverse/cellect_panoptes/blob/4c7dc39745a0490eae56fef62cf3e7e203d1b9ee/start#L13

**Comment by camallen** [comment]
Are you testing it with fig? if so you need to modify the fig.yml to be:

```yaml
postgres:
  image: zooniverse/postgresql
  environment:
    - "PG_USER=panoptes"
    - "DB=panoptes_development"
    - "PASS=panoptes"
```
